# Generated by Django 4.1.3 on 2022-11-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
