# Generated by Django 4.1.3 on 2022-11-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_task_list_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task_list',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
